//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Cus_ID { get; set; }
        public string Cus_Name { get; set; }
        public string cus_Email { get; set; }
        public string Cus_Phone { get; set; }
        public string Cus_Address { get; set; }
        public string Usser_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
