//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Categary
    {
        public Food_Categary()
        {
            this.Food_Court = new HashSet<Food_Court>();
        }
    
        public int ID { get; set; }
        public string Categary_Name { get; set; }
    
        public virtual ICollection<Food_Court> Food_Court { get; set; }
    }
}
